// <auto-generated />
namespace MarketDss.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddExDateToSecurity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExDateToSecurity));
        
        string IMigrationMetadata.Id
        {
            get { return "201804042347272_AddExDateToSecurity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
